output_folder = "test-output"
max_depth = 3
rounds = 5
samples = 1
array_min_len = 1
array_max_len = 5
string_min_len = 1
string_max_len = 5
struct_min_fields = 1
struct_max_fields = 5
enum_min_variants = 1
enum_max_variants = 5
tuple_min_len = 1
tuple_max_len = 5
vector_min_len = 1
vector_max_len = 5
slice_min_len = 1
slice_max_len = 5
bytes_min_len = 1
bytes_max_len = 5